matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: node_js
      node_js: "8"

    - os: linux
      services: docker
      language: generic

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

notifications:
    slack: bitfocusio:Kf9NGYG60SzXkZ2tJO8wIknp

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_install:
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv yarn-v* $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - git config --file=.gitmodules submodule.bitfocus-skeleton.url https://github.com/bitfocus/bitfocus-skeleton.git
  - git config --file=.gitmodules submodule.bitfocus-libs.url https://github.com/bitfocus/bitfocus-libs.git
  - git submodule sync
  - git submodule init
  - git submodule update

install:
  - ./tools/build_writefile.sh


script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        haakonn/electron-wine:v1 \
        /bin/bash -c "apt-get update && apt-get install -y git ; cd bitfocus-skeleton ; yarn ; cd ../bitfocus-libs ; yarn ; cd .. ; yarn --link-duplicates --pure-lockfile && npm run lindist";
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cd bitfocus-skeleton
      yarn
      cd ..
      cd bitfocus-libs
      yarn
      cd ..
      yarn
      npm run dist
    fi
  - ./tools/build_rename_git.sh

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
