osx_image: xcode8.3
dist: precise
sudo: false
language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_install:
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv yarn-v* $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - git config --file=.gitmodules submodule.bitfocus-skeleton.url https://github.com/bitfocus/bitfocus-skeleton.git
  - git config --file=.gitmodules submodule.bitfocus-libs.url https://github.com/bitfocus/bitfocus-libs.git
  - git submodule sync
  - git submodule init
  - git submodule update

install:
  - cd bitfocus-skeleton
  - yarn
  - cd ..
  - cd bitfocus-libs
  - yarn
  - cd ..
  - ./tools/build_writefile.sh
  - yarn


script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run linuxdist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

after_success:
  "curl -v -T electron-output/*.dmg -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_IP/deploy/"
