image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 9 x64
  - sed 's/git@github.com:bitfocus\/bitfocus-skeleton.git/https:\/\/github.com\/bitfocus\/bitfocus-skeleton.git/g' .git/config > .git/config
  - sed 's/git@github.com:bitfocus\/bitfocus-libs.git/https:\/\/github.com\/bitfocus\/bitfocus-libs.git/g' .git/config > .git/config
  - git submodule sync
  - git submodule init
  - git submodule update
  - yarn

build_script:
  - yarn windist

test: off
