image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 9 x64
  - if "%PLATFORM%" == "x64" curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
  - if "%PLATFORM%" == "x86" curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win32.exe
  - yasm --version
  - git config --file=.gitmodules submodule.bitfocus-skeleton.url https://github.com/bitfocus/bitfocus-skeleton.git
  - git config --file=.gitmodules submodule.bitfocus-libs.url https://github.com/bitfocus/bitfocus-libs.git
  - git submodule sync
  - git submodule init
  - git submodule update
  - cmd: bash tools/yarn.sh
  - cmd: bash tools/build_writefile.sh
  - yarn

environment:
  TRAVIS_OS_NAME: win64

artifacts:
  - path: electron-output/*.exe
    name: Installer

build_script:
  - yarn windist
  - cmd: bash tools/build_rename_git.sh

test: off

deploy:
  - provider: FTP
    host: 80.241.92.222
    protocol: ftp
    username: companion
    password:
      secure: ONk7QHFaaI9JaZ+frqLkRZ+oYjdTgrwTVm21ZX3K0lg=
    folder: deploy
