name: Node CI
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.12]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        yarn update
        yarn run lindist
        ./tools/build_rename_git.sh
      env:
        CI: true
    - name: S3 Upload
      uses: peter-evans/s3-backup@v1.0.0
      env:
        ACCESS_KEY_ID: ${{ secrets.BITFOCUS_ACCESS }}
        SECRET_ACCESS_KEY: ${{ secrets.BITFOCUS_SECRET }}
        STORAGE_SERVICE_URL: https://s3.bitfocus.io
        STORAGE_SERVICE_ALIAS: minio
        MIRROR_SOURCE: ./electron-output/artifact/
        MIRROR_TARGET: builds/companion/
  macos:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [8.12]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        yarn update
        yarn run macdist
        ./tools/build_rename_git.sh
      env:
        CI: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: mac-build
        path: electron-output/
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [8.12]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        yarn update
        yarn run windist
      env:
        CI: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windows-build
        path: electron-output/